coverage:
  status:
    project: off
    patch: off

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "core/*"
  - "examples/shared/*"
