#!/bin/sh
#
# MIT License
#
# Copyright (c) 2018 8devices
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

set -e

PROJECT_ROOT_DIR="$(cd $(dirname "$0")/.. && pwd -P)"
PROJECT_BUILD_DIR="${PROJECT_ROOT_DIR}/build"
SCRIPTS_DIR="${PROJECT_ROOT_DIR}/script"

build_wakaama () {
    cmake_arguments=""
    eval "rm -rf ${PROJECT_BUILD_DIR}" | true
    eval "mkdir ${PROJECT_BUILD_DIR}"

    if ! [ -z "$1" ]; then
        cmake_arguments="${cmake_arguments} $1"
    fi

    if ! [ $? -eq 0 ]; then
        echo "Failed to create build directory!"
        return 1
    fi

    eval "cd ${PROJECT_BUILD_DIR}"
    echo "cmake ${cmake_arguments} ${PROJECT_ROOT_DIR}"
    eval "cmake ${cmake_arguments} ${PROJECT_ROOT_DIR}"
    make
    cd -
}

eval "${SCRIPTS_DIR}/bootstrap"

echo "==> Building punica..."
build_wakaama "$@"
